export const propertyListings = [
  {
    id: 1,
    price: 350000,
    location: "123 Maple St, Springfield, IL",
    rooms: 3,
    baths: 2,
    type: "Single Family Home",
    imageRef: "/sale/h3.jpg",
  },
  {
    id: 2,
    price: 275000,
    location: "456 Oak Ave, Rivertown, TX",
    rooms: 2,
    baths: 1,
    type: "Townhouse",
    imageRef: "/sale/h2.jpg",
  },
  {
    id: 3,
    price: 450000,
    location: "789 Pine Rd, Lakeside, CA",
    rooms: 4,
    baths: 3,
    type: "Condo",
    imageRef: "/sale/house1.jpg",
  },
  {
    id: 4,
    price: 560000,
    location: "321 Birch Blvd, Hilltop, CO",
    rooms: 5,
    baths: 4,
    type: "Luxury Home",
    imageRef: "/sale/h4.jpg",
  },
  {
    id: 5,
    price: 230000,
    location: "654 Cedar Ln, Greenfield, OH",
    rooms: 3,
    baths: 2,
    type: "Single Family Home",
    imageRef: "/sale/h5.jpg",
  },
  {
    id: 6,
    price: 180000,
    location: "987 Elm St, Brooksville, FL",
    rooms: 2,
    baths: 1,
    type: "Apartment",
    imageRef: "/sale/h6.jpg",
  },
  {
    id: 7,
    price: 375000,
    location: "135 Willow Dr, Valleyview, WA",
    rooms: 4,
    baths: 2,
    type: "Single Family Home",
    imageRef: "/sale/h7.jpg",
  },
  {
    id: 8,
    price: 490000,
    location: "246 Spruce Ct, Maplewood, NJ",
    rooms: 4,
    baths: 3,
    type: "Duplex",
    imageRef: "/sale/h8.jpg",
  },
  {
    id: 9,
    price: 295000,
    location: "357 Ash Pl, Pine Valley, AZ",
    rooms: 3,
    baths: 2,
    type: "Ranch",
    imageRef: "/sale/h9.jpg",
  },
  {
    id: 10,
    price: 620000,
    location: "468 Fir Ln, Oceanview, MA",
    rooms: 5,
    baths: 4,
    type: "Villa",
    imageRef: "/sale/h10.jpg",
  },
];
